# Generated by Django 3.2.8 on 2026-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_employee_stripe_connect_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payout_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
    ]
