# Generated by Django 3.2.8 on 2026-08-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_payout_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar (USD)'), ('aud', 'Australian Dollar (AUD)'), ('gbp', 'British Pound (GBP)'), ('eur', 'Euro (EUR)'), ('cad', 'Canadian Dollar (CAD)'), ('bdt', 'Bangladeshi Taka (BDT)'), ('inr', 'Indian Rupee (INR)'), ('sgd', 'Singapore Dollar (SGD)'), ('aed', 'UAE Dirham (AED)')], default='usd', max_length=10),
        ),
    ]
