# Generated by Django 3.2.8 on 2026-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organization_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='moderator_can_add_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='moderator_can_manage_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
