# Generated by Django 3.2.8 on 2026-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_organization_moderator_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
