# Generated by Django 3.2.8 on 2026-08-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_organization_subscription_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='moderator_can_manage_qr',
            field=models.BooleanField(default=False),
        ),
    ]
