# Generated by Django 3.2.8 on 2026-08-26 04:02

from django.db import migrations, models


def backfill_currency_from_org(apps, schema_editor):
    Employee = apps.get_model('authentication', 'Employee')
    for employee in Employee.objects.select_related('organization').exclude(organization__isnull=True):
        Employee.objects.filter(pk=employee.pk).update(currency=employee.organization.currency)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_organization_moderator_can_manage_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar (USD)'), ('aud', 'Australian Dollar (AUD)'), ('gbp', 'British Pound (GBP)'), ('eur', 'Euro (EUR)'), ('cad', 'Canadian Dollar (CAD)'), ('bdt', 'Bangladeshi Taka (BDT)'), ('inr', 'Indian Rupee (INR)'), ('sgd', 'Singapore Dollar (SGD)'), ('aed', 'UAE Dirham (AED)')], default='usd', max_length=10),
        ),
        migrations.RunPython(backfill_currency_from_org, migrations.RunPython.noop),
    ]
