# Generated by Django 3.2.8 on 2026-08-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_employee_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payout_cycle',
            field=models.CharField(choices=[('hourly', 'Hourly (instant, right after each shift)'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
    ]
