# Generated by Django 3.2.8 on 2026-08-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_employee_payout_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payout_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
