# Generated by Django 3.2.8 on 2026-08-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_organization_payout_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_payout_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
