# Generated by Django 3.2.8 on 2026-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_user_org_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
