# Generated by Django 3.2.8 on 2026-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_shift_reminders_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='silent_mode',
            field=models.BooleanField(default=False),
        ),
    ]
