# Generated by Django 3.2.8 on 2026-08-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=29, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=290, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'US Dollar (USD)'), ('aud', 'Australian Dollar (AUD)'), ('gbp', 'British Pound (GBP)'), ('eur', 'Euro (EUR)'), ('cad', 'Canadian Dollar (CAD)'), ('bdt', 'Bangladeshi Taka (BDT)'), ('inr', 'Indian Rupee (INR)'), ('sgd', 'Singapore Dollar (SGD)'), ('aed', 'UAE Dirham (AED)')], default='usd', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
