# Generated by Django 3.2.8 on 2026-09-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
