# Generated by Django 3.2.8 on 2026-08-26 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_employee_currency'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('new_currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_changes_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='authentication.organization')),
            ],
            options={
                'verbose_name_plural': 'Rate histories',
                'ordering': ('-created_at',),
            },
        ),
    ]
