# Generated by Django 3.2.8 on 2026-08-30 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_auto_20260830_1552'),
        ('authentication', '0011_organization_default_payout_payment_method_id'),
        ('wallet', '0002_ratehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAdjustmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('overtime', 'Overtime'), ('shortfall', 'Shortfall')], max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=wallet.models.pay_adjustment_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('granted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manager_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_adjustment_requests', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_adjustment_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_adjustment_requests', to='authentication.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_adjustments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
