# Generated by Django 3.2.8 on 2026-09-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_payadjustmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting employee confirmation'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=25),
        ),
    ]
