# Generated by Django 3.2.8 on 2026-09-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_walletransaction_cash_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payadjustmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting employee confirmation'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', max_length=25),
        ),
    ]
