# Generated by Django 3.2.8 on 2026-09-17 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_silent_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(default='sales', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('source', models.CharField(default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_income', to='authentication.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_income', to='authentication.organization')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['organization', 'date'], name='expense_inc_organiz_da8301_idx'),
        ),
    ]
