# Generated by Django 3.2.8 on 2026-08-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('roster_assigned', 'Roster assigned'), ('leave_submitted', 'Leave submitted'), ('leave_reviewed', 'Leave reviewed'), ('rate_changed', 'Pay rate changed'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
