# Generated by Django 3.2.8 on 2026-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scheduled_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shortfall_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('roster_assigned', 'Roster assigned'), ('leave_submitted', 'Leave submitted'), ('leave_reviewed', 'Leave reviewed'), ('rate_changed', 'Pay rate changed'), ('pay_adjustment_submitted', 'Pay adjustment requested'), ('pay_adjustment_reviewed', 'Pay adjustment reviewed'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
