# Generated by Django 3.2.8 on 2026-09-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20260830_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('roster_assigned', 'Roster assigned'), ('leave_submitted', 'Leave submitted'), ('leave_reviewed', 'Leave reviewed'), ('rate_changed', 'Pay rate changed'), ('pay_adjustment_submitted', 'Pay adjustment requested'), ('pay_adjustment_reviewed', 'Pay adjustment reviewed'), ('cash_payout_pending', 'Cash payout awaiting your confirmation'), ('cash_payout_confirmed', 'Cash payout confirmed'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
