# Generated by Django 3.2.8 on 2026-09-04 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0015_remove_user_org_role'),
        ('attendance', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('roster_assigned', 'Roster assigned'), ('leave_submitted', 'Leave submitted'), ('leave_reviewed', 'Leave reviewed'), ('rate_changed', 'Pay rate changed'), ('pay_adjustment_submitted', 'Pay adjustment requested'), ('pay_adjustment_reviewed', 'Pay adjustment reviewed'), ('cash_payout_pending', 'Cash payout awaiting your confirmation'), ('cash_payout_confirmed', 'Cash payout confirmed'), ('swap_requested', 'Shift swap requested'), ('swap_claimed', 'Shift swap claimed'), ('swap_reviewed', 'Shift swap reviewed'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending_peer', 'Awaiting a colleague'), ('pending_manager', 'Awaiting manager approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_peer', max_length=20)),
                ('manager_note', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_claimed', to='authentication.employee')),
                ('proposed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_received', to='authentication.employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='authentication.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='attendance.roster')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='authentication.employee')),
            ],
            options={
                'verbose_name_plural': 'Availability',
                'ordering': ('day_of_week',),
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
    ]
