# Generated by Django 3.2.8 on 2026-09-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_availability_and_shift_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='days_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
