# Generated by Django 3.2.8 on 2026-09-06 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_leavetype_days_per_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='roster',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='status',
            field=models.CharField(choices=[('pending_peer', 'Awaiting a colleague'), ('pending_manager', 'Awaiting manager approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_peer', max_length=20),
        ),
    ]
