# Generated by Django 4.2.11 on 2026-09-06 08:22

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=attendance.models.leave_request_attachment_upload_path),
        ),
    ]
