# Generated by Django 3.2.8 on 2026-09-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_leaverequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('roster_assigned', 'Roster assigned'), ('leave_submitted', 'Leave submitted'), ('leave_reviewed', 'Leave reviewed'), ('rate_changed', 'Pay rate changed'), ('pay_adjustment_submitted', 'Pay adjustment requested'), ('pay_adjustment_reviewed', 'Pay adjustment reviewed'), ('cash_payout_pending', 'Cash payout awaiting your confirmation'), ('cash_payout_confirmed', 'Cash payout confirmed'), ('swap_requested', 'Shift swap requested'), ('swap_claimed', 'Shift swap claimed'), ('swap_reviewed', 'Shift swap reviewed'), ('shift_reminder', 'Upcoming shift reminder'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
