"""
Django settings for start_project project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original dev key so local setups keep working untouched;
# set SECRET_KEY in the environment for any real deployment.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-u-e(&(%d#(e+gj+nel$(-gefvmg$uwr9v747d7c8^&hqo8amh@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
	'rest_framework',
	'corsheaders',
	'drf_spectacular',
	'phonenumber_field',
	'djoser',
    'django_filters',
    'channels',

    #local
    'authentication.apps.AuthenticationConfig',
    'cms.apps.CmsConfig',
    'site_settings.apps.SiteSettingsConfig',
    'support.apps.SupportConfig',
	'url_shortener.apps.UrlShortenerConfig',
	'attendance.apps.AttendanceConfig',
	'billing.apps.BillingConfig',
	'wallet.apps.WalletConfig',
	"expense.apps.ExpenseConfig",
	'chat.apps.ChatConfig',
]

INSTALLED_APPS += ['sequences.apps.SequencesConfig']

# Render's web dyno filesystem is ephemeral — anything saved to MEDIA_ROOT
# (profile photos, leave-request attachments, pay-adjustment proof images)
# is wiped on every deploy. Cloudinary's free tier is used to persist
# uploads instead, but only once real credentials are supplied — with no
# CLOUDINARY_* env vars set, this is a no-op and MEDIA_ROOT below still
# works exactly as before (matches the EMAIL_BACKEND fallback pattern).
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '')
USE_CLOUDINARY = bool(CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET)

if USE_CLOUDINARY:
    # Must load before django.contrib.staticfiles per django-cloudinary-storage's docs.
    INSTALLED_APPS = ['cloudinary_storage', 'cloudinary'] + INSTALLED_APPS

MIDDLEWARE = [
    # Simplified static file serving.
    # https://warehouse.python.org/project/whitenoise/
	'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
]


ROOT_URLCONF = 'start_project.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'start_project.wsgi.application'
ASGI_APPLICATION = 'start_project.asgi.application'

# Chat's WebSocket consumer (chat/consumers.py) fans messages out through
# this channel layer — Redis so it works across multiple server processes,
# not just in-memory within one. REDIS_URL is a new required env var
# wherever this app is deployed (see chat feature's ops notes); falls back
# to a local default so `runserver` + a local `redis-server` just works.
#
# socket_keepalive/health_check_interval/retry_on_timeout: Render's managed
# Redis silently drops a connection that's been idle for a while (no TCP
# FIN/RST, it just stops responding), which otherwise surfaces in prod as an
# unhandled `redis.exceptions.TimeoutError: Timeout reading from ...` deep
# inside the consumer's receive loop — killing that one WebSocket (the
# client's own reconnect logic recovers it, but it's a real gap + log spam).
# health_check_interval makes redis-py proactively PING idle connections and
# recycle dead ones before they're used for a real command; socket_keepalive
# adds OS-level TCP keepalives so a silently-dropped connection is detected
# sooner; retry_on_timeout retries once on a fresh connection instead of
# blowing up the whole consumer if a command does still hit a timeout.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [{
                'address': os.environ.get('REDIS_URL', 'redis://localhost:6379/0'),
                'socket_keepalive': True,
                'retry_on_timeout': True,
                'health_check_interval': 30,
            }],
        },
    },
}

AUTH_USER_MODEL = 'authentication.User'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# DATABASE_URL (set by Neon/Render/Railway/etc.) takes over in production;
# falls back to the original local Postgres settings when it's unset, so
# local dev is untouched.
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default='postgres://postgres:12345@localhost/employee_db',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_L10N = True

USE_TZ = True


WHITENOISE_USE_FINDERS = True
CORS_ALLOW_ALL_ORIGINS=True

CORS_ALLOWED_ORIGINS = [
    # "http://127.0.0.1:3000",
    # "https://example.com",
    # "https://sub.example.com",
    # "http://localhost:8080",
    # "https://dreamtourism_it.com",
    
]

FRONTEND_BASE_URL = 'https://dreamtourism.it'

BACKEND_BASE_URL = 'https://api.dreamtourism.it'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # media files upload directory
MEDIA_URL = '/media/' # media files retrieve directory

if USE_CLOUDINARY:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Read from the environment, never hardcoded — set EMAIL_HOST_USER/
# EMAIL_HOST_PASSWORD (e.g. a Gmail App Password, or any real SMTP account)
# on the server once you have one. Until then, with no EMAIL_HOST_USER set,
# this falls back to Django's console backend — emails are printed to the
# server log instead of actually sending, so the send-email code paths
# (employee-created credentials, password reset, etc.) can be verified
# without a real mailbox.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_USER else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@timetap.app')
ADMIN_EMAIL = DEFAULT_FROM_EMAIL
SUPPORT_EMAIL = DEFAULT_FROM_EMAIL
SERVER_EMAIL = DEFAULT_FROM_EMAIL




REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_simplejwt.authentication.JWTAuthentication',
  ),
  'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
  'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'TOURISM_IT',
    'DESCRIPTION': '',
    'VERSION': '1.0.0',
    # OTHER SETTINGS
		# available SwaggerUI configuration parameters
    # https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        # "displayOperationId": True,
    },
    # available SwaggerUI versions: https://github.com/swagger-api/swagger-ui/releases
    "SWAGGER_UI_DIST": "//unpkg.com/swagger-ui-dist@3.35.1", # default
    # "SWAGGER_UI_FAVICON_HREF": STATIC_URL + "your_company_favicon.png", # default is swagger favicon
		# "APPEND_COMPONENTS": {
		# "securitySchemes": {
		# 		"ApiKeyAuth": {
		# 				"type": "apiKey",
		# 				"in": "header",
		# 				"name": "Authorization"
		# 		}
		# 	}
    # },
    # "SECURITY": [{"ApiKeyAuth": [], }],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    # 'SIGNING_KEY': settings.SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}



DJOSER = {

    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'SET_USERNAME_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
        'SERIALIZERS': {
        'user_create': 'authentication.serializers.UserSerializer',
        'user': 'authentication.serializers.UserSerializer',
        'current_user': 'authentication.serializers.UserSerializer',
        'user_delete': 'djoser.  .UserDeleteSerializer',
        }
}

INTERNAL_IPS = [
    "127.0.0.1",
    "192.168.0.151",
    "192.168.0.116",
]


# Stripe (multi-tenant SaaS billing) — read from environment, never hardcoded.
# Test-mode keys are fine for local dev. Leave unset and the billing
# endpoints respond with 503 instead of crashing.
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_PRICE_MONTHLY = os.environ.get('STRIPE_PRICE_MONTHLY', '')
STRIPE_PRICE_YEARLY = os.environ.get('STRIPE_PRICE_YEARLY', '')

# Shared secret an external scheduler (cron-job.org, UptimeRobot, ...)
# passes as ?key=... to hit attendance/api/v1/attendance/cron/send_shift_reminders/
# every 10-15 minutes over plain HTTP — see runShiftReminders. Empty by
# default so that endpoint refuses every request (503) until this is set,
# rather than being callable by anyone with the URL.
CRON_SECRET_KEY = os.environ.get('CRON_SECRET_KEY', '')

_SAAS_FRONTEND_URL = os.environ.get('SAAS_FRONTEND_URL', 'http://127.0.0.1:5173')
BILLING_SUCCESS_URL = os.environ.get('BILLING_SUCCESS_URL', f'{_SAAS_FRONTEND_URL}/?billing=success&session_id={{CHECKOUT_SESSION_ID}}')
BILLING_CANCEL_URL = os.environ.get('BILLING_CANCEL_URL', f'{_SAAS_FRONTEND_URL}/?billing=cancel')
BILLING_RETURN_URL = os.environ.get('BILLING_RETURN_URL', _SAAS_FRONTEND_URL)



 
