# Generated by Django 3.2.8 on 2026-09-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_silent_mode'),
        ('expense', '0002_auto_20260917_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='expense',
            name='uploaded_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expense-receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='authentication.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expense.expensecategory'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='expense_category_org_name_uniq'),
        ),
    ]
