# Generated by Django 3.2.8 on 2026-09-17 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_silent_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0003_auto_20260917_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_audit_logs', to='authentication.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['organization', 'created_at'], name='expense_fin_organiz_942465_idx'),
        ),
    ]
