# Generated by Django 3.2.8 on 2026-09-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20260917_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ('name',), 'verbose_name': 'Expense category', 'verbose_name_plural': 'Expense categories'},
        ),
    ]
