// Centralized backend path builders. Several of these have inconsistent
// naming in the Django backend (e.g. the "without_paginaiton" typo on
// employee) — kept in one place on purpose so the typo only has to live here.

export const endpoints = {
  today: () => `/attendance/api/v1/attendance/today/`,
  checkin: () => `/attendance/api/v1/attendance/checkin/`,
  checkout: () => `/attendance/api/v1/attendance/checkout/`,
  attendanceByEmployee: (id, params = "") => `/attendance/api/v1/attendance/get_all_by_employee_id/${id}${params}`,
  attendanceSearch: (params = "") => `/attendance/api/v1/attendance/search/${params}`,
  attendanceAll: (params = "") => `/attendance/api/v1/attendance/all/${params}`,
  qrImage: (branchId) => `/attendance/api/v1/attendance/qr_token/${branchId}/image/`,
  qrLive: (branchId) => `/attendance/api/v1/attendance/qr_token/${branchId}/live/`,
  qrRegenerate: (branchId) => `/attendance/api/v1/attendance/qr_token/${branchId}/regenerate/`,
  qrGeofence: (branchId) => `/attendance/api/v1/attendance/qr_token/${branchId}/geofence/`,
  exportPdf: (params = "") => `/attendance/api/v1/attendance/export/pdf/${params}`,
  exportExcel: (params = "") => `/attendance/api/v1/attendance/export/excel/${params}`,
  markAbsent: (params = "") => `/attendance/api/v1/attendance/mark_absent/${params}`,

  timesheet: (params = "") => `/attendance/api/v1/timesheet/${params}`,
  timesheetExportCsv: (params = "") => `/attendance/api/v1/timesheet/export/csv/${params}`,
  timesheetExportPdf: (params = "") => `/attendance/api/v1/timesheet/export/pdf/${params}`,
  timesheetExportExcel: (params = "") => `/attendance/api/v1/timesheet/export/excel/${params}`,

  rosterByEmployee: (id, params = "") => `/roster/api/v1/roster/get_all_by_employee_id/${id}${params}`,
  rosterAll: (params = "") => `/roster/api/v1/roster/all/${params}`,
  rosterCreate: () => `/roster/api/v1/roster/create/`,

  availabilityMine: () => `/availability/api/v1/mine/`,
  availabilityMineUpdate: () => `/availability/api/v1/mine/update/`,
  availabilityByEmployee: (id) => `/availability/api/v1/employee/${id}/`,
  availabilityAll: () => `/availability/api/v1/all/`,

  shiftSwapRequest: () => `/shift_swap/api/v1/request/`,
  shiftSwapMine: () => `/shift_swap/api/v1/mine/`,
  shiftSwapRespond: (pk) => `/shift_swap/api/v1/${pk}/respond/`,
  shiftSwapCancel: (pk) => `/shift_swap/api/v1/${pk}/cancel/`,
  shiftSwapAll: () => `/shift_swap/api/v1/all/`,
  shiftSwapReview: (pk) => `/shift_swap/api/v1/${pk}/review/`,

  shiftsAll: () => `/shift/api/v1/shift/without_pagination/all/`,
  shiftCreate: () => `/shift/api/v1/shift/create/`,
  shiftUpdate: (pk) => `/shift/api/v1/shift/update/${pk}`,
  shiftDelete: (pk) => `/shift/api/v1/shift/delete/${pk}`,

  leaveTypesAll: () => `/leave_type/api/v1/leave_type/without_pagination/all/`,
  leaveTypeCreate: () => `/leave_type/api/v1/leave_type/create/`,
  leaveTypeDelete: (pk) => `/leave_type/api/v1/leave_type/delete/${pk}`,

  leaveRequestCreate: () => `/leave_request/api/v1/leave_request/create/`,
  leaveRequestByEmployee: (id, params = "") => `/leave_request/api/v1/leave_request/get_all_by_employee_id/${id}${params}`,
  leaveRequestAll: (params = "") => `/leave_request/api/v1/leave_request/all/${params}`,
  leaveRequestReview: (pk) => `/leave_request/api/v1/leave_request/review/${pk}`,
  leaveBalanceMine: () => `/leave_request/api/v1/leave_request/balance/mine/`,

  employeesAll: () => `/employee/api/v1/employee/without_paginaiton/all/`,
  teammatesAll: () => `/employee/api/v1/employee/teammates/`,
  employeeCreate: () => `/employee/api/v1/employee/create/`,
  employeeUpdate: (pk) => `/employee/api/v1/employee/update/${pk}`,

  branchesAll: () => `/branch/api/v1/branch/without_pagination/all/`,
  branchCreate: () => `/branch/api/v1/branch/create/`,

  notificationsMine: (params = "") => `/notification/api/v1/notification/mine/${params}`,
  notificationMarkRead: (pk) => `/notification/api/v1/notification/mark_read/${pk}`,
  notificationMarkAllRead: () => `/notification/api/v1/notification/mark_all_read/`,

  djoserMe: () => `/djoser/auth/users/me/`,
  djoserResetPassword: () => `/djoser/auth/users/reset_password/`,
  djoserResetPasswordConfirm: () => `/djoser/auth/users/reset_password_confirm/`,
  djoserSetPassword: () => `/djoser/auth/users/set_password/`,

  registerPushToken: () => `/account/api/v1/push_token/`,
  deactivateAccount: () => `/account/api/v1/deactivate/`,
  profileMe: () => `/account/api/v1/me/`,
  profileUpdate: () => `/account/api/v1/me/update/`,

  signup: () => `/saas/api/v1/signup/`,
  organizationsAll: () => `/saas/api/v1/organizations/`,
  organizationCommission: (id) => `/saas/api/v1/organizations/${id}/commission/`,

  billingStatus: () => `/billing/api/v1/status/`,
  billingCheckout: () => `/billing/api/v1/checkout/`,
  billingCustomerPortal: () => `/billing/api/v1/customer_portal/`,
  billingConfirm: () => `/billing/api/v1/confirm/`,
  platformSettings: () => `/billing/api/v1/platform_settings/`,
  organizationSettings: () => `/billing/api/v1/organization/settings/`,
  payoutCardStatus: () => `/billing/api/v1/payout_card/status/`,
  payoutCardSetup: () => `/billing/api/v1/payout_card/setup/`,
  payoutCardConfirm: () => `/billing/api/v1/payout_card/confirm/`,

  walletMe: () => `/wallet/api/v1/me/`,
  walletPayoutRequest: () => `/wallet/api/v1/payout/request/`,
  connectOnboard: () => `/wallet/api/v1/connect/onboard/`,
  connectStatus: () => `/wallet/api/v1/connect/status/`,
  payrollSummary: () => `/wallet/api/v1/payroll/summary/`,
  payrollRun: () => `/wallet/api/v1/payroll/run/`,
  payrollExportCsv: (params = "") => `/wallet/api/v1/payroll/export/csv/${params}`,
  payrollExportPdf: (params = "") => `/wallet/api/v1/payroll/export/pdf/${params}`,
  payrollExportExcel: (params = "") => `/wallet/api/v1/payroll/export/excel/${params}`,
  payoutReview: (pk) => `/wallet/api/v1/payout/${pk}/review/`,
  payoutConfirm: () => `/wallet/api/v1/payout/confirm/`,
  payoutConfirmCash: (pk) => `/wallet/api/v1/payout/${pk}/confirm_cash/`,
  payoutPayCash: (employeeId) => `/wallet/api/v1/payout/pay_cash/${employeeId}/`,
  walletTransactions: (params = "") => `/wallet/api/v1/transactions/${params}`,
  payAdjustmentEligible: () => `/wallet/api/v1/pay_adjustment/eligible/`,
  payAdjustmentRequest: () => `/wallet/api/v1/pay_adjustment/request/`,
  payAdjustmentMine: () => `/wallet/api/v1/pay_adjustment/mine/`,
  payAdjustmentAll: (params = "") => `/wallet/api/v1/pay_adjustment/all/${params}`,
  payAdjustmentReview: (pk) => `/wallet/api/v1/pay_adjustment/${pk}/review/`,
  payAdjustmentAccept: (pk) => `/wallet/api/v1/pay_adjustment/${pk}/accept/`,
  rateHistory: (employeeId) => `/wallet/api/v1/rate_history/${employeeId}/`,
};
